# Generated by Django 4.2.6 on 2023-11-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('phone', models.PositiveBigIntegerField(unique=True)),
                ('password', models.CharField(max_length=30)),
                ('repassword', models.CharField(max_length=30)),
            ],
        ),
    ]
